version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo-list
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Add initialization script

  todo-list-service:
    build:
      context: ./todo-list-service
    container_name: todo-list-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://todoUser:todoPassword@mongodb:27017/todo-list?authSource=admin
      - JWT_SECRET=sflkjashfo9w48yfnqunc9q07rfh24nc
    depends_on:
      - mongodb

  todo-list-app:
    build:
      context: ./todo-list-app
    container_name: todo-list-app
    ports:
      - "8080:80"
    depends_on:
      - todo-list-service

volumes:
  mongodb_data:
